apiVersion: v1
kind: Service
metadata:
  name: my-app-stable
spec:
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-preview
spec:
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: my-app-stable
      previewService: my-app-preview
      autoPromotionEnabled: true
      autoPromotionSeconds: 0
  progressDeadlineSeconds: 60   # rollback if pods not healthy in 60s
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: docker.io/onkarkulkarni545/my-app:89cb7f102ee2462dc900a6943501a1199577cf23
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:         # health probe
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
