apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: onkarkulkarni545/my-app:9f8cd2ef1d95d8cf6b709878d5115a53f369d714
        ports:
        - containerPort: 3000

