apiVersion: v1
kind: Service
metadata:
  name: my-app-stable
spec:
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-preview
spec:
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: my-app-stable
      previewService: my-app-preview
      autoPromotionEnabled: true
      autoPromotionSeconds: 0          # (optional) promote immediately if healthy
      scaleDownDelaySeconds: 0         # immediately scale down failed preview pods
      abortScaleDownDelaySeconds: 0
    
  progressDeadlineSeconds: 30   # rollback if pods not healthy in 60s
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: docker.io/onkarkulkarni545/my-app:af678cfb9c6cb721d7db653a8a505056e855572e
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:         
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

